### PR TITLE
SECURITY-1401 Add method to disable su

### PR DESCRIPTION
**Pull request by bsper2**
su is disabled by setting the permissions to 0700

By default su will be disabled, this behavior can be changed in hiera

### CODE REVIEW

**Comment by bsper2** [comment]
Tested on bsper2-pupclient

I've defaulted to disabling su, which is probably best from a security perspective. This seems like a fine thing to go ahead and update in ncsa/control-repo, but maybe some care is needed before pushing this change into asd-pup? Not sure if any of those systems rely on su but it seems like a decent chance.

**Review by jakerundall — COMMENTED** [review]
The Puppet code/approach looks good to me. @billglick should probably weigh in too?

I guess that merging to main and bumping production on GitHub wouldn't affect asd-pup but we'd have to be aware that the changes are in main moving forward.

But bumping production here on GitHub  _would_ directly affect control-pup01, right?

**Comment by bsper2** [comment]
Correct bumping version in ncsa/control-repo won't change anything on asd-pup, so that can be bumped later down the road if we are worried there might be some nodes that will be negatively impacted with this. Alternatively we could just bump up asd-pup to the new version and then override `profile_system_auth::su::disable_su: false` in hiera and thrown in an ASDPLNG ticket to sometime later lock this down more and only override on nodes that actually need it.

Bumping up ncsa/control-repo would impact control-pup01, but there are only test nodes there for now and shouldn't be anything that needs su so that should be ok.

**Comment by billglick** [comment]
@v1peractual (David) has some code for Delta for letting staff, e.g. User Services, impersonate a user in a protected mode. I haven't looked at how that is happening, but suspect it may make use of `su`.

At the very least I want to make @v1peractual aware that this su work is in progress and to comment on it.

**Comment by v1peractual** [comment]
This is something I am working on. I will update this when I get back to it. It will be very soon. It uses sudo and not su. I don't think this will have an issue, unless there is a dependency that I don't know of. 

```
#!/usr/bin/perl

# sudo to a user with their correct shell
# relies on the sudoers.d
# keep a script for logging and verification purposes using sudoreplay
# manipulate the history file to make it seem the user has never been impersonated

my $user = shift or die "Usage: $0 username\n";
my $id = `/usr/bin/getent passwd $user` or die "No such user: $user\n";
( my $homedir, my $sh ) = $id =~ m/.*:.*:.*:.*:(\S+):(\S+)$/;

my $U = $ENV{LOGNAME} || $ENV{USER} || getpwuid($<);
my $D = qx( date +%Y%m%d%H%M%S );
chomp $D;
my $HF = "$homedir/.$user.$U.$D";

if( $sh =~ m/bash/ ){
  exec "/usr/bin/sudo -i -u $user HISTTIMEFORMAT='<%F %T> ' HISTFILE=$HF HISTFILESIZE=1000";
}
elsif( $sh =~ m/csh/ ){
  exec "/usr/bin/sudo -u $user /usr/bin/tcsh -c 'cp -p ~/.history ~/.history.sav; /usr/bin/tcsh -l; mv ~/.history $HF; mv ~/.history.sav ~/.history;' ";
}
elsif( $sh =~ m/zsh/ ){ # for the few iconoclasts
  exec "/usr/bin/sudo -u $user /usr/bin/zsh -c 'if [ -z \$HISTFILE ]; then HISTFILE=~/.zsh_history; fi; cp -p \$HISTFILE \$HISTFILE.sav; /usr/bin/zsh -l; mv \$HISTFILE $HF; mv \$HISTFILE.sav \$HISTFILE; '";
  #exec "/usr/bin/sudo -u $user /usr/bin/zsh -c 'cp -p $HISTFILE $HISTFILE.sav; /usr/bin/zsh -l; mv $HISTFILE $HF; mv $HISTFILE.sav $HISTFILE; '";
  ####exec "/usr/bin/sudo -u $user /usr/bin/zsh -c 'cp -p ~/.zhistory ~/.zhistory.sav; /usr/bin/zsh -l; mv ~/.zhistory $HF; mv ~/.zhistory.sav ~/.zhistory; '";
}
else {
  print "User's shell not found: $user with shell $sh\n";
  die "Contact bw-admin@ncsa.illinois.edu\n";
}
```

**Comment by bsper2** [comment]
Ok that's good to know, since it's using sudo this change to su shouldn't break anything.

This change should be ok to move forward on ncsa/control-repo at least.

For updating asd-pup-control I like the idea of bumping up the latest tag of this module, and then overriding  `profile_system_auth::su::disable_su: false` so it won't make any config changes. Then get a ASDPLNG ticket to lock it down more.

**Review by jakerundall — APPROVED** [review]
Looks good!

**Pull request merged**
